    /*
    프로그래머스 sql 문제
    # 1. 인기있는 아이스크림
    SELECT FLAVOR
    FROM FIRST_HALF
    ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC

    # 2. 모든 레코드 조회하기
    SELECT ANIMAL_ID , ANIMAL_TYPE, DATETIME, INTAKE_CONDITION ,NAME,SEX_UPON_INTAKE
    FROM ANIMAL_INS
    ORDER BY ANIMAL_ID ASC

    # 3. 역순 정렬하기
    SELECT NAME , DATETIME
    FROM ANIMAL_INS
    ORDER BY ANIMAL_ID DESC

    # 4. 동물의 아이디와 이름
    SELECT ANIMAL_ID , NAME
    FROM ANIMAL_INS
    ORDER BY  ANIMAL_ID ASC

    # 5. 여러 기준으로 정렬하기
    SELECT ANIMAL_ID , NAME	, DATETIME
    FROM  ANIMAL_INS
    ORDER BY  NAME ASC , DATETIME DESC

    #6. 과일로 만든 아이스크림 고르기
    SELECT FIRST_HALF.FLAVOR
    FROM FIRST_HALF INNER JOIN ICECREAM_INFO
    ON FIRST_HALF.FLAVOR  =  ICECREAM_INFO.FLAVOR
    WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
    ORDER BY FIRST_HALF.TOTAL_ORDER DESC


    #7.강원도에 위치한 생산공장 목록 출력하기
    SELECT FACTORY_ID , FACTORY_NAME , ADDRESS
    FROM FOOD_FACTORY
    WHERE ADDRESS LIKE '%강원도%'
    ORDER BY FACTORY_ID ASC

    #8. 아픈 동물 찾기
    SELECT ANIMAL_ID ,  NAME
    FROM  ANIMAL_INS
    WHERE INTAKE_CONDITION LIKE '%SICK%'
    ORDER BY ANIMAL_ID  ASC


    #9. 어린 동물 찾기
    SELECT  ANIMAL_ID , NAME
    FROM ANIMAL_INS
    WHERE INTAKE_CONDITION NOT LIKE '%AGED%'
    ORDER BY ANIMAL_ID ASC


    #10. 상위 n개 레코드
    SELECT NAME
    FROM ANIMAL_INS
    ORDER BY DATETIME ASC
    LIMIT 1


    #11. Python 개발자 찾기
    SELECT ID ,EMAIL , FIRST_NAME , LAST_NAME
    FROM DEVELOPER_INFOS
    WHERE SKILL_1 LIKE '%Python%'
    OR SKILL_2 LIKE '%Python%'
    OR SKILL_3 LIKE '%Python%'
    ORDER BY ID ASC




    */